# Generated by Django 5.2.9 on 2025-12-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Konteynerga nom (masalan: my-nginx)', max_length=100)),
                ('image', models.CharField(help_text='Docker Image (masalan: nginx:latest)', max_length=100)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('host_port', models.IntegerField(help_text='Tashqi port (masalan: 8080)')),
                ('container_port', models.IntegerField(default=80, help_text='Ichki port (masalan: 80)')),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('exited', 'Exited'), ('created', 'Created')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
